// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Reporting.Models;

namespace Reporting.Migrations
{
    [DbContext(typeof(ReportingContext))]
    [Migration("20210812143750_MyMigration")]
    partial class MyMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Reporting.Models.WaFac", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Agctrn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CatAbt")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DatExgFact")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DatFact")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateMaj")
                        .HasColumnType("datetime2");

                    b.Property<string>("Dop")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EtaFact")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LibcategAbt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("MntFact")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("Numtrn")
                        .HasColumnType("int");

                    b.Property<string>("TypFact")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypFactRef")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("WaFacs");
                });
#pragma warning restore 612, 618
        }
    }
}
