// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Reporting.Models;

namespace Reporting.Migrations
{
    [DbContext(typeof(ReportingContext))]
    [Migration("20210814175127_ReportingMig")]
    partial class ReportingMig
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Reporting.Models.ListeAgence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NOM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProdsId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProdsId");

                    b.ToTable("ListeAgence");
                });

            modelBuilder.Entity("Reporting.Models.Prods", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Libele")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Prods");
                });

            modelBuilder.Entity("Reporting.Models.WaFacs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AGCTRN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CAT_ABT")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DATE_MAJ")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DAT_EXG_FACT")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DAT_FACT")
                        .HasColumnType("datetime2");

                    b.Property<string>("DOP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ETA_FACT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LIBCATEG_ABT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("MNT_FACT")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("NUMTRN")
                        .HasColumnType("int");

                    b.Property<string>("TYP_FACT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TYP_FACT_REF")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("WaFacs");
                });

            modelBuilder.Entity("Reporting.Models.ListeAgence", b =>
                {
                    b.HasOne("Reporting.Models.Prods", "Prods")
                        .WithMany("ListeAgence")
                        .HasForeignKey("ProdsId");

                    b.Navigation("Prods");
                });

            modelBuilder.Entity("Reporting.Models.Prods", b =>
                {
                    b.Navigation("ListeAgence");
                });
#pragma warning restore 612, 618
        }
    }
}
