// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Reporting.Models;

namespace Reporting.Migrations
{
    [DbContext(typeof(ReportingContext))]
    partial class ReportingContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Reporting.Models.Dop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool?>("IsSelected")
                        .HasColumnType("bit");

                    b.Property<string>("Libele")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Dop");
                });

            modelBuilder.Entity("Reporting.Models.ListeAgence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Id_DOP")
                        .HasColumnType("int");

                    b.Property<string>("NOM")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Id_DOP");

                    b.ToTable("ListeAgence");
                });

            modelBuilder.Entity("Reporting.Models.Repositerie.wa_fraudes", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("COORD_X")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("COORD_Y")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DAT_EXG_FAC_CLI")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DAT_FAC_CLI")
                        .HasColumnType("datetime2");

                    b.Property<string>("DOP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ID_FAC_CLI")
                        .HasColumnType("int");

                    b.Property<string>("IG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LATI_LONG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LIB_CAT_ABT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LIB_TRN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("MNT_AV")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MNT_FAC")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MNT_FAC_AV")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("NUM_CLI")
                        .HasColumnType("int");

                    b.Property<int>("NUM_CTA_ABT")
                        .HasColumnType("int");

                    b.Property<int>("NUM_TRN_RLV_ABT")
                        .HasColumnType("int");

                    b.Property<string>("PNO_CLI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("QTE")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RAI_SOC_CLI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RPG_APT_PNT_DRT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TYP_FACT_ORI")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("wa_fraudes");
                });

            modelBuilder.Entity("Reporting.Models.WaFacs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AGCTRN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CAT_ABT")
                        .HasColumnType("int");

                    b.Property<DateTime>("DATE_MAJ")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DAT_EXG_FACT")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DAT_FACT")
                        .HasColumnType("datetime2");

                    b.Property<string>("DOP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ETA_FACT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LIBCATEG_ABT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("MNT_FACT")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("NUMTRN")
                        .HasColumnType("int");

                    b.Property<string>("TYP_FACT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TYP_FACT_REF")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("WaFacs");
                });

            modelBuilder.Entity("Reporting.Models.wa_cat_abt", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("libcateg_abt")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("wa_cat_abt");
                });

            modelBuilder.Entity("Reporting.Models.ListeAgence", b =>
                {
                    b.HasOne("Reporting.Models.Dop", "Dop")
                        .WithMany("ListeAgence")
                        .HasForeignKey("Id_DOP")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dop");
                });

            modelBuilder.Entity("Reporting.Models.Dop", b =>
                {
                    b.Navigation("ListeAgence");
                });
#pragma warning restore 612, 618
        }
    }
}
